language: php

git:
  depth: 1

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

  include:
    # php 5.5
    - php: 5.5
    - php: 5.5
      env: setup=lowest
    # php 5.6
    - php: 5.6
    - php: 5.6
      env: setup=lowest
    # php 7.0
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    # php 7.1
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    # php 7.2
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    # php 7.3
    - php: 7.3
    - php: 7.3
      env: setup=lowest
    # code-style
    - php: 7.2
      env: setup=style
    # test + coverage
    - php: 7.2
      env: setup=coverage
    # static code analysis
    - php: 7.2
      env: setup=analysis
    # php nightly
    - php: nightly
    - php: nightly
      env: setup=lowest
    # hhvm
    - php: hhvm
    - php: hhvm-nightly

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - if [[ $setup != 'coverage' ]]; then phpenv config-rm xdebug.ini || true; fi
  - if [[ $setup != 'lowest'   ]]; then travis_retry composer update -n --no-suggest; fi
  - if [[ $setup  = 'lowest'   ]]; then travis_retry composer update -n --no-suggest --prefer-lowest; fi

script:
  - if [[ $setup = 'stable'   ]]; then composer test; fi
  - if [[ $setup = 'lowest'   ]]; then composer test; fi
  - if [[ $setup = 'style'    ]]; then composer cs; fi
  - if [[ $setup = 'coverage' ]]; then composer kahlan; fi
  - if [[ $setup = 'analysis' ]]; then composer phpstan; fi

after_success:
  - if [[ $setup = 'coverage' ]]; then bash <(curl -s https://codecov.io/bash); fi
  - if [[ $setup = 'coverage' ]]; then curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs --verbose; fi
