language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor

sudo: false

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
  - composer test
  - phpenv config-rm xdebug.ini || return 0
  - composer cs
