language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - 5.5 # phpspec requires php 5.6+
    - hhvm
    - 7.2

before_script:
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpspec run --format=pretty -vvv
